CREATE TABLE CLIENTS(
    CLIENT_ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    SECTOR VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    NUMBER_OF_CONSULTANTS INT
);

CREATE TABLE CONSULTANTS(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    ABLE_TO_RELOCATE BOOLEAN,
    CURRENT_CLIENT INT,
    FOREIGN KEY (CURRENT_CLIENT) REFERENCES CLIENTS(CLIENT_ID)
);
