INSERT INTO CLIENTS(CLIENT_ID, NAME, SECTOR, LOCATION, NUMBER_OF_CONSULTANTS) VALUES (DEFAULT, 'M&S', 'Retail','London','12');
INSERT INTO CLIENTS(CLIENT_ID,NAME, SECTOR, LOCATION, NUMBER_OF_CONSULTANTS) VALUES (DEFAULT, 'Lloyds Bank', 'Finance','Manchester', '6');
INSERT INTO CLIENTS(CLIENT_ID,NAME, SECTOR, LOCATION, NUMBER_OF_CONSULTANTS) VALUES (DEFAULT, 'Barclays','Finance', 'London', '12');

INSERT INTO CONSULTANTS(ID, NAME, LOCATION, ABLE_TO_RELOCATE, CURRENT_CLIENT) VALUES (DEFAULT, 'Jess','Bristol', TRUE,1);
INSERT INTO CONSULTANTS(ID, NAME, LOCATION, ABLE_TO_RELOCATE, CURRENT_CLIENT) VALUES (DEFAULT, 'Bob','London', FALSE,3);